export const sampleProviders = [
  {
    id: '1',
    slug: 'sarah-mitchell',
    name: 'Sarah Mitchell',
    title: 'Private Practice Medical Secretary',
    tier: 'Elite',
    specialty: 'ENT / Head & Neck',
    location: 'London, UK',
    rating: 4.9,
    reviews: 128,
    price: '£45/hr',
    delivery: 'Same-day replies',
    tagline: 'Harley Street-level clinic coordination, diaries, letters, and patient liaison.',
    services: ['Clinic diary', 'Patient communication', 'Letters'],
  },
  {
    id: '2',
    slug: 'amir-patel',
    name: 'Amir Patel',
    title: 'Medical Billing & Insurance Specialist',
    tier: 'Elite',
    specialty: 'Private Billing',
    location: 'Manchester, UK',
    rating: 4.8,
    reviews: 86,
    price: 'From £650/mo',
    delivery: 'Weekly reporting',
    tagline: 'Insurer billing, shortfalls, reconciliation, and revenue tracking for consultants.',
    services: ['eBilling', 'Shortfalls', 'Reconciliation'],
  },
  {
    id: '3',
    slug: 'emma-clarke',
    name: 'Emma Clarke',
    title: 'Medical PA & Clinic Administrator',
    tier: 'Marketplace',
    specialty: 'General Private Practice',
    location: 'Bristol, UK',
    rating: 4.7,
    reviews: 42,
    price: '£28/hr',
    delivery: '24-hour turnaround',
    tagline: 'Flexible admin support for consultants needing part-time clinic help.',
    services: ['Admin', 'Inbox triage', 'Bookings'],
  },
];
